[shell]

program = "/bin/zsh"
args = ["-l"]

[window]

dimensions = { columns = 100, lines = 25 }

# padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Dark"

title = "Alacritty"
dynamic_title = false

[font]

# normal = {family = "UbuntuMono Nerd Font", style = "Regular"}
normal = { family = "VictorMono Nerd Font", style = "SemiBold"}
# bold = { style = "Bold" }
# italic = { style = "Italic" }
# bold_italic = { style = "Bold Italic" }
# 14.4, 15.7, 17.5 Идеально по размерам окна при использовании Ubuntu Font и dynamic_padding = false.
# 12.3, 13.8 Идеально для VictorMono Nerd Font
size = 12.3

[mouse]

hide_when_typing = true

[keyboard]

# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    # { key = "Key", mods = "Modifiers", action = "Любая из доступных команд" chars = "Characters to send" },
    # ...
]

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

# [colors]
# [[colors.indexed_colors]]
# index = 16
# color = "0xff9e64"
#
# [[colors.indexed_colors]]
# index = 17
# color = "0xdb4b4b"
#
# [colors.primary]
# background = "0x1a1b26"
# foreground = "0xc0caf5"
#
# [colors.normal]
# black = "0x15161E"
# red = "0xf7768e"
# green = "0x9ece6a"
# yellow = "0xe0af68"
# blue = "0x7aa2f7"
# magenta = "0xbb9af7"
# cyan = "0x7dcfff"
# white = "0xa9b1d6"
#
# [colors.bright]
# black = "0x414868"
# red = "0xf7768e"
# green = "0x9ece6a"
# yellow = "0xe0af68"
# blue = "0x7aa2f7"
# magenta = "0xbb9af7"
# cyan = "0x7dcfff"
# white = "0xc0caf5"
